import type { Metadata } from "next";
import { Manrope, Playfair_Display} from "next/font/google";
import "./globals.css";
import { Header, Preloader } from "./components";
import Footer from "./components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
});
const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  style: "italic"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${manrope.className} ${playfair.variable} h-full antialiased`}
    >
      <head>
        <link rel="manifest" href="public/favicon/site.webmanifest" />
      </head>
      <body className="min-h-full flex flex-col">
        <Preloader />
        <Header />

        <main className="flex-1">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
